name: Inputs and Outputs
on: 
    workflow_dispatch:
        inputs:
            dry-run:
                description: salida del proceso
                type: boolean
                default: false
            target:
                description: Which environment the workflow will target
                type: environment
                required: true
            tag:
                description: Release from which to build and deploy
                type: choice
                options:
                    - V1
                    - V2
                    - V3
                default: V3
            build-status:
                description: Choose the build status for the demo
                type: choice
                options:
                    - success
                    - failure
                default: success
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "GITHUB_OUTPUT path: $GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          echo "status=${{ github.event.inputs.build-status }}" >> $GITHUB_OUTPUT
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      tag: ${{ github.event.inputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' && github.event.inputs.dry-run == 'false' && needs.build.outputs['build-status'] == 'success' }}
    environment: ${{ github.event.inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.target }} using tag ${{ needs.build.outputs.tag }}"
